version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: ecommerce_db
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password_sicura
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_admin -d ecommerce_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce_net

  backend:
    build: ./backend
    container_name: ecommerce_backend
    # TODO: use .env file
    environment:
      DATABASE_URL: "postgresql://user_admin:password_sicura@db:5432/ecommerce_db?schema=public"
      PORT: 3008
    ports:
      - "3008:3008"
    volumes:
      - ./backend:/app # Mappa la cartella locale 'backend' in '/app' nel container
      - /app/node_modules # Protegge i moduli installati nel container (CORRETTO)
    command: sh -c "npx prisma generate &&
      npx prisma db push &&
      npx tsx prisma/seed.ts &&
      npm run dev"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ecommerce_net

  frontend:
    build: ./frontend
    container_name: ecommerce_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app # Mappa la cartella locale in /app
      - /app/node_modules # Protegge i moduli (NON usare ./frontend/node_modules)
      - /app/.next # Protegge la cache di Next.js (NON usare ./frontend/.next)
    # TODO: use .env file
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3008/api
      - WATCHPACK_POLLING=true
    networks:
      - ecommerce_net
    depends_on:
      - backend

networks:
  ecommerce_net:
    driver: bridge

volumes:
  postgres_data:
